services:
  - type: web
    name: nexloan-api
    env: docker
    region: oregon
    plan: free
    dockerContext: backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_VISION_MODEL
        value: llama-3.2-11b-vision-preview
      - key: GROQ_TEXT_MODEL
        value: llama-3.1-8b-instant
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: EMAIL_FROM
        value: "mayurdoiphode55@gmail.com"
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_PUBLIC_URL
        sync: false
      - key: DEBUG
        value: "false"
