"""phase5_revenue_risk_ops_analytics

Revision ID: eabd049c8f0c
Revises: f6a7b8c9d0e1
Create Date: 2026-05-02 14:02:17.587940+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabd049c8f0c'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('is_topup', sa.Boolean(), nullable=True))
    op.add_column('loans', sa.Column('parent_loan_id', sa.UUID(), nullable=True))
    op.add_column('loans', sa.Column('topup_previous_outstanding', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('sourced_by_agent_id', sa.UUID(), nullable=True))
    op.add_column('loans', sa.Column('loan_metadata', sa.JSON(), nullable=True))
    op.drop_constraint('loans_collateral_verified_by_fkey', 'loans', type_='foreignkey')
    op.create_foreign_key(None, 'loans', 'agents', ['sourced_by_agent_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'loans', 'loans', ['parent_loan_id'], ['id'])
    op.add_column('tenant_config', sa.Column('bureau_mode', sa.String(length=20), nullable=True))
    op.add_column('tenant_config', sa.Column('bureau_weight', sa.Float(), nullable=True))
    op.add_column('tenant_config', sa.Column('bureau_api_key', sa.String(length=500), nullable=True))
    op.add_column('tenant_config', sa.Column('bureau_enabled', sa.Boolean(), nullable=True))
    op.add_column('tenant_config', sa.Column('referral_reward_amount', sa.Float(), nullable=True))
    op.add_column('tenant_config', sa.Column('benchmark_report_email', sa.String(length=200), nullable=True))
    op.add_column('tenant_config', sa.Column('benchmark_report_enabled', sa.Boolean(), nullable=True))
    op.add_column('tenant_config', sa.Column('benchmark_report_day', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reward_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reward_balance')
    op.drop_column('tenant_config', 'benchmark_report_day')
    op.drop_column('tenant_config', 'benchmark_report_enabled')
    op.drop_column('tenant_config', 'benchmark_report_email')
    op.drop_column('tenant_config', 'referral_reward_amount')
    op.drop_column('tenant_config', 'bureau_enabled')
    op.drop_column('tenant_config', 'bureau_api_key')
    op.drop_column('tenant_config', 'bureau_weight')
    op.drop_column('tenant_config', 'bureau_mode')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.create_foreign_key('loans_collateral_verified_by_fkey', 'loans', 'users', ['collateral_verified_by'], ['id'])
    op.drop_column('loans', 'loan_metadata')
    op.drop_column('loans', 'sourced_by_agent_id')
    op.drop_column('loans', 'topup_previous_outstanding')
    op.drop_column('loans', 'parent_loan_id')
    op.drop_column('loans', 'is_topup')
    # ### end Alembic commands ###
